### ISSUE TITLE
can`t scan images 

### ISSUE THREAD

**Issue by Nello-Angelo** [stackrox/stackrox#10867]
<img width="116" alt="Screenshot at Apr 24 13-10-28" src="https://github.com/stackrox/stackrox/assets/82488489/4c0dde4b-8c22-4d7a-a5b6-a7aba730d51c">

<img width="1726" alt="Screenshot at Apr 24 01-43-11" src="https://github.com/stackrox/stackrox/assets/82488489/2ae183ea-2353-484b-aae3-1cea8a6c274b">
<img width="1727" alt="Screenshot at Apr 24 01-43-33" src="https://github.com/stackrox/stackrox/assets/82488489/e61d2b10-9ed7-44f1-9cac-fe4173613caa">

**Comment by Nello-Angelo** [comment]
"image not scanned" i understand how to fix but there are images that can`t be scanned with warning on the second screen

**Comment by Nello-Angelo** [comment]
i use old scanner

**Comment by RTann** [comment]
Thank you for raising this issue.

I see the three screenshots.

First:

I see just a list of "operating systems" (in quotes because busybox is not really an OS). Is there a question related to this?

Second:

That note is inaccurate, and it should be resolved in a release soon. The older, StackRox Scanner, was not able to dynamically update that notice. The new Scanner V4 does have the ability to dynamically update it

Third:

You mention you know how to fix the "image not scanned" issue. Were you able to resolve it?

**Comment by Nello-Angelo** [comment]
Third: 

not i could not resolve this problem with hurbor and custom private registry(i work at cloud provider)

**Comment by Nello-Angelo** [comment]
i connected to harbor but i still get an error "image not scanned"

**Comment by daynewlee** [comment]
For "image cannot be scanned"
Have you tried this command?
roxctl image scan --force --image=<registry/image:tag>

**Comment by Nello-Angelo** [comment]
no

**Comment by kurlov** [comment]
@Nello-Angelo 
did the above recommendation worked for you?

**Comment by Nello-Angelo** [comment]
i did not used

**Comment by Nello-Angelo** [comment]
i have 2 images from one registry and one of two images - stackrox scan correct but second image in front has error. Why this happen?

```
CVE data may be inaccurate
Failed to retrieve metadata from the registry.
Check the registry connection.
```

**Comment by porridge** [comment]
Judging on the messages you pasted, sounds like scanner is having issues fetching metadata from your registry?
Were you able to investigate or resolve this?

**Comment by AkakievKD** [comment]
no

**Comment by porridge** [comment]
I would suggest you try the roxctl command provided above, and check scanner logs for errors relating to registry connection.

**Comment by porridge** [comment]
Closing due to lack of updates for 6+ months.
