### ISSUE TITLE
signature verification policy intermittently failing

### ISSUE THREAD

**Issue by jsolis** [stackrox/stackrox#5472]
We have all our images being signed using `cosign` at build time using a Google KMS key and pushed to GCR (Google's Container Registry). I can see the signatures are there.

I put the public key in the Signature Integration, setup a policy in StackRox using the field `Not verified by trusted image signers` and added the signature integration, turned on build and deploy lifecycle stages.

Most of the time, I'd say over 90% the Policy verifies the signature with no problem. But roughly 10% of the time, we are getting Violations for this policy for images that definitely have a valid signature in GCR. If I run `roxctl check` on that same image, it will not report a violation of this policy. And If I redeploy the same image again, the violation usually gets cleared up.

We'd like to turn deploy time enforcement of this policy on, but due to the above intermittent and seemingly erroneous violations of the policy, I cannot. And for what it's worth, all other policies are behaving correctly.

I have checked the logs and do not find any smoking guns.

**Comment by janisz** [comment]
Are you on version 3.74? The issue was fixed by @dhaus67's PRs. It occurs when the same image is downloaded from multiple registries, but only one registry has the correct signature.
- https://github.com/stackrox/stackrox/pull/3511

**Comment by jsolis** [comment]
Yes, we are running `v3.74.1`. We only have our images in a single registry, Google's GCR. We never upload them anywhere else. We do have multiple registry connectors configured, but these images are never uploaded to a second one

**Comment by porridge** [comment]
@stackrox/merlin can you please take a look at this image signing verification issue?

**Comment by dhaus67** [comment]
Hey!

Apologies for the long delay on answering this issue.

We've done a few improvements to the signature verification as well as fetching, and hopefully issues like that shouldn't arise anymore.

Still, it would be great to get the following, in case you are still having issues with it with later version (talking about > 4.2.0):
When the issue occurs, may I ask you to past the output of the API call `/v1/images/<sha256:<image digest>` for the images that are creating the false-positive violations? In the response, you may strip away anything besides the `Name, Names, Signature, SignatureVerificationData` values. This would help us the most during figuring out what is going on.

Again, sorry for the inconvenience of this huge delay.

**Comment by jasonsolis** [comment]
Thank you for following up here.

We are running 4.3.0 and I'm still getting what I believe are false positives for only some images. I can see the signatures in GCR the same as I can for others that are not violating.

API response for `/v1/iimages/<sha256>`

```
{
    "name": {
        "registry": "gcr.io",
        "remote": "pcln-pl-gcr-prod/fir/fly-maestro-book",
        "tag": "1.75",
        "fullName": "gcr.io/pcln-pl-gcr-prod/fir/fly-maestro-book:1.75"
    },
    "names": [
        {
            "registry": "gcr.io",
            "remote": "pcln-pl-gcr-prod/fir/fly-maestro-book",
            "tag": "1.75",
            "fullName": "gcr.io/pcln-pl-gcr-prod/fir/fly-maestro-book:1.75"
        }
    ],
    "signatureVerificationData": {
        "results": [
            {
                "verificationTime": "2024-03-26T18:51:09.036335204Z",
                "verifierId": "io.stackrox.signatureintegration.43394e74-e185-4b67-8a66-ae485dbc5af0",
                "status": "VERIFIED",
                "description": "",
                "verifiedImageReferences": [
                    "gcr.io/pcln-pl-gcr-prod/fir/fly-maestro-book:1.75"
                ]
            }
        ]
    },
    "signature": {
        "signatures": [
            {
                "cosign": {
                    "rawSignature": "MEQCIC680gyDUo4CGx2YMDUugKahcoWqzR7WRqFBvNA2RiZ9AiAzzQKZJ2139C+/F6lKhi4ZmHFa4yPugR8y4xDKsnvUag==",
                    "signaturePayload": "eyJjcml0aWNhbCI6eyJpZGVudGl0eSI6eyJkb2NrZXItcmVmZXJlbmNlIjoiZ2NyLmlvL3BjbG4tcGwtZ2NyLXByb2QvZmlyL2ZseS1tYWVzdHJvLWJvb2sifSwiaW1hZ2UiOnsiZG9ja2VyLW1hbmlmZXN0LWRpZ2VzdCI6InNoYTI1NjplNzM1YTM5Mzg0Njk4NzlkMzliMjUxY2ZkOWEyMzdlMWVmNGNjNjExN2JiNWY1MDdjN2YzMzljMTlkZjJkYmFjIn0sInR5cGUiOiJjb3NpZ24gY29udGFpbmVyIGltYWdlIHNpZ25hdHVyZSJ9LCJvcHRpb25hbCI6bnVsbH0="
                }
            }
        ],
        "fetched": "2024-03-26T18:51:09.034642824Z"
    },
```

**Comment by porridge** [comment]
@dhaus67 any updates from your side?

**Comment by dhaus67** [comment]
Thank you for providing the output @jasonsolis.

By the looks of the API output, the following checks out:

We've got one successful verification result, which matches the given image reference
```json
        "results": [
            {
                "status": "VERIFIED",
                "verifiedImageReferences": [
                    "gcr.io/xxxx-pl-gcr-prod/fir/fly-maestro-book:1.75"
                ]
            }
        ]
```
and the contents of the signature payload also seem to match (just for clarification: the digest of the image is `sha256:e735a3938469879d39b251cfd9a237e1ef4cc6117bb5f507c7f339c19df2dbac`, right?).

One additional culprit could also be the following: ACS periodically scans images; this is called "enrichment". Enrichment also includes fetching signatures associated with the scanned image, as well as verifying those.
During those runs, it might be that for some reason there was an error during fetching signatures - within Central logs when the intermittent failure occurs, do you see something along the lines of:
```log
reprocessor: Error: Error enriching image {"image": "gcr.io/xxxx-pl-gcr-prod/fir/fly-maestro-book:1.75", "error": "image enrichment error: fetching image signatures ..."}
```

This would help us narrow things down.

**Comment by jasonsolis** [comment]
My apology for not following up here sooner. After upgrading to `v4.5.4` a little while back, we don't seem to have this issue anymore. We still have findings but they all seem to be legit findings were the signature is missing. Thanks for following up here but I think we're good now.
